// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'dialog-apply'
  | 'dialog-cancel'
  | 'dialog-column-change'
  | 'dialog-column-creators'
  | 'dialog-column-title'
  | 'dialog-done'
  | 'dialog-empty-state'
  | 'dialog-explanation'
  | 'dialog-heading'
  | 'dialog-iso-link-href'
  | 'dialog-iso-link-text'
  | 'dialog-opt-convert'
  | 'dialog-opt-overwrite'
  | 'dialog-skip-hint'
  | 'dialog-title'
  | 'dialog-unchanged'
  | 'menu-classify'
  | 'progress-classify-headline'
  | 'progress-items-processed';
